
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OJD-Student
 */
public class AddFeeForm extends javax.swing.JFrame {
    String name1,fname1,course1,courseid1,cduration1,status1;
    int coursefee1,cdiscount1,r_amount1;
       String studentid1;
       

    /**
     * Creates new form AddFeeForm
     */
    public AddFeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        fetchFeeRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("FEE FORM");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 4, 3, 4, new java.awt.Color(255, 153, 153)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 130, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("STUDENT ID:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, 30));
        getContentPane().add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 320, 30));

        fetchFeeRecord.setBackground(new java.awt.Color(204, 204, 255));
        fetchFeeRecord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fetchFeeRecord.setText("SUBMIT");
        fetchFeeRecord.setBorder(null);
        fetchFeeRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchFeeRecordActionPerformed(evt);
            }
        });
        getContentPane().add(fetchFeeRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchFeeRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchFeeRecordActionPerformed
        // TODO add your handling code here:
     studentid1=studentid.getText().toString().trim();
     
        
        if(studentid.getText().equals("")){
           studentid.setBackground(Color.red);
           JFrame ob=new JFrame();
            JOptionPane.showMessageDialog(ob, "Id, can not blank");
    
}

else
{
       System.out.println("studentid="+studentid1);
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdb","root","");
        String sql="select name,fname,course,courseid,coursefee,payment_remain,discount,duration,status from add_fee where studentid ='"+studentid1+"' ";
       Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(sql);
        while(rs.next())
        {
               
              name1=rs.getString("name");
               fname1=rs.getString("fname");
               course1=rs.getString("course");
               courseid1=rs.getString("courseid");
               cduration1=rs.getString("duration");
                status1=rs.getString("status");
               coursefee1=Integer.parseInt(rs.getString("coursefee"));
                cdiscount1=Integer.parseInt(rs.getString("discount"));
                 r_amount1=Integer.parseInt(rs.getString("payment_remain"));
                
                System.out.println("studentid="+name1+fname1+course1+courseid1+coursefee1+cduration1+cdiscount1+r_amount1+status1);
                
          
        //Going to sumbit fee form        
                
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmitFeeForm(studentid1,name1,fname1,course1,courseid1,coursefee1,cduration1,cdiscount1,r_amount1,status1).setVisible(true);
            }
        });
                                   
        }
        
    }
         
           
        

        
    catch (ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
                    }
    }//GEN-LAST:event_fetchFeeRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fetchFeeRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField studentid;
    // End of variables declaration//GEN-END:variables
}
