
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OJD-Student
 */
public class Print_Record_Form extends javax.swing.JFrame {
     String rcptno1,studentid1,course1,courseid1,duration1,discount1,coursefee1,payment1,payment_remain1,issued_date1;
   String name1,fname1,status1;
    public Print_Record_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rcptno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        studentid2 = new javax.swing.JLabel();
        course2 = new javax.swing.JLabel();
        courseid2 = new javax.swing.JLabel();
        duration2 = new javax.swing.JLabel();
        discount2 = new javax.swing.JLabel();
        coursefee2 = new javax.swing.JLabel();
        payment2 = new javax.swing.JLabel();
        pay_remain2 = new javax.swing.JLabel();
        issue_date2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PRINT RECORD");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("RECIPT NO:");

        rcptno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcptnoActionPerformed(evt);
            }
        });

        jLabel3.setText("STUDENT ID:");

        jLabel4.setText("COURSE:");

        jLabel5.setText("COURSE ID:");

        jLabel6.setText("DURATION:");

        jLabel7.setText("DISCOUNT:");

        jLabel8.setText("COURSE FEE:");

        jLabel9.setText(" LAST PAYMENT");

        jLabel10.setText("PAYMENT REMAIN:");

        jLabel11.setText("DATE:");

        studentid2.setText("student id");

        course2.setText("course");

        courseid2.setText("courseid");

        duration2.setText("duration");

        discount2.setText("discount");

        coursefee2.setText("course fee");

        payment2.setText("payment");

        pay_remain2.setText("payment remain");

        issue_date2.setText("issued date");

        jLabel21.setText("STATUS:");

        status2.setText("status");

        submit.setBackground(new java.awt.Color(255, 102, 102));
        submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit.setText("SUBMIT");
        submit.setBorder(null);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(153, 153, 255));
        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("PRINT");
        print.setBorder(null);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(rcptno, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(26, 26, 26))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(course2)
                            .addComponent(studentid2)
                            .addComponent(courseid2)
                            .addComponent(duration2)
                            .addComponent(pay_remain2)
                            .addComponent(issue_date2)
                            .addComponent(status2)
                            .addComponent(discount2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(coursefee2)
                                .addComponent(payment2))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(12, 12, 12))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(rcptno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(studentid2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(course2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(courseid2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(duration2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(discount2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(coursefee2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(payment2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pay_remain2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(issue_date2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(status2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(print)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:// TODO add your handling code here:
        if(rcptno.getText().equals("")){
      rcptno.setBackground(Color.red);
    JFrame ob=new JFrame();
    JOptionPane.showMessageDialog(ob, "Plz enter rcptno ");
    
} 
        try{
            rcptno1=rcptno.getText().toString().trim();
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdb","root","");
       String sql1="select name,fname,status from add_fee where rcptno='"+rcptno1+"'";
        String sql="select * from feebook where rcptno='"+rcptno1+"'";
        
       Statement st=con.createStatement();
       Statement st1=con.createStatement();
        ResultSet rs2=st1.executeQuery(sql1);
         ResultSet rs=st.executeQuery(sql);
         while(rs2.next())
        {
          name1=rs2.getString("name");
          fname1=rs2.getString("fname");
         status1=rs2.getString("status");
          
           
        }
          System.out.println("add_fee_record="+name1+" "+fname1+" "+status1+"");
          

        
       
        
          while(rs.next())
        {
          rcptno1=rs.getString("rcptno");
          studentid1=rs.getString("studentid");
          course1=rs.getString("course");
          courseid1=rs.getString("courseid");
          duration1=rs.getString("duration");
          discount1=rs.getString("discount");
          coursefee1=rs.getString("coursefee");
          payment1=rs.getString("payment");
          payment_remain1=rs.getString("payment_remain");
          issued_date1=rs.getString("issued_date");
            System.out.println("single_record="+rcptno1+" "+studentid1+" "+course1+" "+courseid1+" "+duration1+" "+discount1+" "+coursefee1+" "+ payment1+""+payment_remain1+""+issued_date1);
          
        }
          studentid2.setText( studentid1);
          course2.setText(course1);
          courseid2.setText(courseid1);
          duration2.setText(duration1);
          discount2.setText(discount1);
          coursefee2.setText(coursefee1);
          payment2.setText(payment1);
          pay_remain2.setText(payment_remain1);
          issue_date2.setText(issued_date1);
          txtReceipt.append("\t\t Ojd Student Fee Receipt\n\n"+
                  "\n==============================================================\n"+
                   "Name:\t\t\t"+name1+"\n\n"+
                   "fatherName:\t\t\t"+fname1+"\n\n"+
                   "feestatus:\t\t\t"+status1+"\n\n"+
                  "studentid:\t\t\t"+studentid2.getText()+"\n\n"+
                    "course:\t\t\t"+course2.getText()+"\n\n"+
                    "courseid:\t\t\t"+courseid2.getText()+"\n\n"+
                    "duration:\t\t\t"+duration2.getText()+"\n\n"+
                    "discount:\t\t\t"+discount2.getText()+"\n\n"+
                    "coursefee:\t\t\t"+coursefee2.getText()+"\n\n"+
                  " Last payment:\t\t\t"+payment2.getText()+"\n\n"+
                  "pay_remain:\t\t\t"+pay_remain2.getText()+"\n\n"+
                  "issued_date:\t\t\t"+issue_date2.getText()+"\n\n"+
                   "\n***************************************************************\n"                
                  
                  
                  
                  
                  
                  
                  );
    rs.close();
     rs2.close();  
    
    }
 catch (ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_submitActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
         try {
             txtReceipt.print();
         } catch (PrinterException ex) {
             Logger.getLogger(Print_Record_Form.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_printActionPerformed

    private void rcptnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcptnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcptnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Record_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Record_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Record_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Record_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Record_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel course2;
    private javax.swing.JLabel coursefee2;
    private javax.swing.JLabel courseid2;
    private javax.swing.JLabel discount2;
    private javax.swing.JLabel duration2;
    private javax.swing.JLabel issue_date2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pay_remain2;
    private javax.swing.JLabel payment2;
    private javax.swing.JButton print;
    private javax.swing.JTextField rcptno;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel studentid2;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
