import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Registration extends javax.swing.JFrame {
    int cf,cid,cdiscount;
    String cduration;
String status="pending";
 int pay_remain=0;
 JFrame ob;
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lb5 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        qualification = new javax.swing.JTextField();
        adhar = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        category = new javax.swing.JComboBox<>();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        lb0 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("REGISTRATION");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 4, 3, 4, new java.awt.Color(51, 51, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 0, 210, 40);

        lb1.setText("NAME:");
        getContentPane().add(lb1);
        lb1.setBounds(150, 90, 50, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 0, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 0, 0);
        getContentPane().add(name);
        name.setBounds(230, 80, 450, 30);

        lb2.setText("FATHER NAME:");
        getContentPane().add(lb2);
        lb2.setBounds(110, 120, 100, 20);
        getContentPane().add(fname);
        fname.setBounds(230, 120, 450, 30);

        lb5.setText("PASSWORD:");
        getContentPane().add(lb5);
        lb5.setBounds(120, 250, 90, 20);

        lb4.setText("E-MAIL:");
        getContentPane().add(lb4);
        lb4.setBounds(140, 210, 60, 20);

        lb3.setText("DATE OF BIRTH:");
        getContentPane().add(lb3);
        lb3.setBounds(100, 160, 110, 20);

        lb8.setText("GENDER:");
        getContentPane().add(lb8);
        lb8.setBounds(140, 390, 80, 14);

        lb9.setText("CATEGORY:");
        getContentPane().add(lb9);
        lb9.setBounds(390, 420, 90, 14);

        lb7.setText("QUALIFICATION:");
        getContentPane().add(lb7);
        lb7.setBounds(100, 340, 120, 14);

        lb6.setText("ADHAR NO:");
        getContentPane().add(lb6);
        lb6.setBounds(130, 300, 90, 20);
        getContentPane().add(dob);
        dob.setBounds(230, 160, 450, 30);
        getContentPane().add(email);
        email.setBounds(230, 200, 450, 30);
        getContentPane().add(qualification);
        qualification.setBounds(230, 330, 450, 30);
        getContentPane().add(adhar);
        adhar.setBounds(230, 290, 450, 30);
        getContentPane().add(password);
        password.setBounds(230, 240, 450, 30);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "OBC", "SC-ST", "OTHER", " " }));
        getContentPane().add(category);
        category.setBounds(480, 420, 71, 20);

        buttonGroup1.add(male);
        male.setText("MALE");
        getContentPane().add(male);
        male.setBounds(220, 380, 51, 23);

        buttonGroup1.add(female);
        female.setText("FEMALE");
        getContentPane().add(female);
        female.setBounds(280, 380, 63, 23);

        lb0.setText("COURSE:");
        getContentPane().add(lb0);
        lb0.setBounds(140, 414, 90, 20);

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BSC", "BTECH", "MCA", "MTECH", "O level", "Java", "Python", "CCC" }));
        getContentPane().add(course);
        course.setBounds(240, 410, 60, 30);

        submit.setBackground(new java.awt.Color(204, 204, 255));
        submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit.setForeground(new java.awt.Color(51, 153, 0));
        submit.setText("SUBMIT");
        submit.setBorder(null);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(260, 480, 150, 29);

        jLabel2.setText("MOBILE NO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 380, 110, 20);
        getContentPane().add(mobile);
        mobile.setBounds(480, 380, 230, 30);

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear.setText("CLEAR ALL");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(500, 480, 170, 29);

        login.setBackground(new java.awt.Color(255, 204, 204));
        login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(51, 0, 51));
        login.setText("LOGIN");
        login.setBorder(null);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(100, 480, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    
     int StudentId = (int)(Math.random()*(100000-10000+1)+10000);  
      System.out.println("StudentId="+StudentId); 
        String name1=name.getText().toString().trim();
      String fname1=fname.getText().toString().trim();
      String dob1=dob.getText().toString().trim();
      String email1=email.getText().toString().trim();
      String password1=password.getText().toString().trim();
      String adhar1=adhar.getText().toString().trim();
      String quali1=qualification.getText().toString().trim();
      String cat1=category.getSelectedItem().toString().trim();
      male.setActionCommand("male");
      female.setActionCommand("female");
      String gender1=buttonGroup1.getSelection().getActionCommand();
      String course1=course.getSelectedItem().toString().trim();
       String mobile1=mobile.getText().toString().trim();
      System.out.println("validated data="+StudentId+name1+fname1+dob1+email1+password1+adhar1+quali1+cat1+gender1+course1+mobile1);
           boolean isValid=isValid(email.getText().trim());
            System.out.println("is valid ="+isValid);
                
            if (name.getText().equals("")) {
                name.setBackground(Color.red);
                JFrame ob=new JFrame();
                JOptionPane.showMessageDialog(ob,"Name cane not blank");
              
            } 
            else if(mobile.getText().length()<10)
            {
            mobile.setBackground(Color.red);
            JFrame ob=new JFrame();
            JOptionPane.showMessageDialog(ob,"check mobile number");
           }
            else if(email.getText().length()==0 && isValid==false)
            {
            email.setBackground(Color.red);
             JFrame ob=new JFrame();
            JOptionPane.showMessageDialog(ob,"email can not blank");
            }
            else if(password.getText().length()<5)
            {
            password.setBackground(Color.red);
             JFrame ob=new JFrame();
            JOptionPane.showMessageDialog(ob,"pass can not blank");
            }
            else if(adhar.getText().length()<12)
            {
            adhar.setBackground(Color.red);
            JFrame ob=new JFrame();
            JOptionPane.showMessageDialog(ob,"adhar can not blank");
            }
            else{
      try {
            
           
            //jdbc connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdb","root","");
            Statement stmt=con.createStatement();         
            stmt.executeUpdate("insert into student_regis(studentid,name,fname,dob,email,password,adharno,quali,cat,gender,course,mobile)values('"+StudentId+"','"+name1+"','"+fname1 +"','"+dob1 +"','"+email1 +"','"+password1 +"','"+adhar1 +"','"+quali1 +"','"+cat1 +"','"+gender1 +"','"+course1 +"','"+mobile1 +"')");
             
            System.out.println("sucessfully inserted");
            //Fectch Course fee
            String sqlfee="Select * from courserecord where course='"+course1+"'";
             ResultSet rs=stmt.executeQuery(sqlfee);
             
             if(rs.next())
             {
               cid=Integer.parseInt(rs.getString("courseid"));
                   cdiscount=Integer.parseInt(rs.getString("discount"));
                   cduration=rs.getString("duration");
               cf=Integer.parseInt(rs.getString("fee"));
                
             }
           
          System.out.println("course="+course1+": "+"fee="+cf+"courseid="+cid+"courseduration="+cduration+"discount="+cdiscount);
          //Fectch Course fee closed
          //Insert Record in student fee
            String addfeeRecord="insert into add_fee(studentid,name,fname,course,courseid,coursefee,payment_remain,duration,discount,status)values('"+StudentId+"','"+name1+"','"+fname1 +"','"+course1 +"','"+cid+"','"+cf+"','"+pay_remain+"','"+cduration+"','"+cdiscount+"','"+status+"')";
            stmt.executeUpdate(addfeeRecord);
            ob=new JFrame();
            JOptionPane.showMessageDialog(ob,"Record Inserted and Fee table Created Successfully");
            
            System.out.println("feeTableupdated");
            stmt.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       name.setText("");
     fname.setText("");
   dob.setText("");
     email.setText("");
     password.setText("");
     adhar.setText("");
      qualification.setText("");
      mobile.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        }); 
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adhar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb0;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JButton login;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField qualification;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

public static boolean isValid(String email)
{
String regex="^(.+)@(.+)$";
Pattern pattern= Pattern.compile(regex);
if(email==null)
    return false;
return pattern.matcher(email).matches();

}
}
